spring.application.name=my-voucher-app
server.port=5555

#connect the database
spring.datasource.url = jdbc:mysql://localhost:3306/projectdb
#set the credentials in the enviroment variables 
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
