spring.application.name=products-rest-api
server.port=5550
# connect the database 
spring.datasource.url = ${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# contextPath 
# server.servlet.context-path=/products$$010*6969
voucherService.url=http://localhost:5555/voucherapi/vouchers/